Split out subquery to prevent a database deadlock
Workaround for
https://github.com/galaxyproject/galaxy/pull/11902/checks?check_run_id=2448536558#step:6:1478

```
ERROR    galaxy.jobs.handler:handler.py:467 failure running job 1082
Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 472 waits for ShareLock on transaction 23258; blocked by process 470.
Process 470 waits for ShareLock on transaction 23259; blocked by process 472.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (6,138) in relation "history"
SQL statement "UPDATE history
                    SET update_time = (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
                    WHERE id = NEW.history_id OR id = OLD.history_id"
PL/pgSQL function update_history_update_time() line 9 at SQL statement

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/handler.py", line 442, in __handle_waiting_jobs
    self.dispatcher.put(self.job_wrappers.pop(job.id))
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/handler.py", line 1046, in put
    self.job_runners[runner_name].put(job_wrapper)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/runners/__init__.py", line 153, in put
    job_wrapper.enqueue()
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/__init__.py", line 1471, in enqueue
    self.change_state(model.Job.states.QUEUED, flush=False, job=job)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/jobs/__init__.py", line 1411, in change_state
    job.update_output_states(self.app.application_stack.supports_skip_locked())
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/model/__init__.py", line 1303, in update_output_states
    self.update_hdca_update_time_for_job(update_time=update_time, sa_session=sa_session, supports_skip_locked=supports_skip_locked)
  File "/home/runner/work/galaxy/galaxy/galaxy root/lib/galaxy/model/__init__.py", line 1207, in update_hdca_update_time_for_job
    sa_session.execute(implicit_statement)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1296, in execute
    clause, params or {}
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
DETAIL:  Process 472 waits for ShareLock on transaction 23258; blocked by process 470.
Process 470 waits for ShareLock on transaction 23259; blocked by process 472.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (6,138) in relation "history"
SQL statement "UPDATE history
                    SET update_time = (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
                    WHERE id = NEW.history_id OR id = OLD.history_id"
PL/pgSQL function update_history_update_time() line 9 at SQL statement

[SQL: UPDATE history_dataset_collection_association SET update_time=%(update_time)s WHERE history_dataset_collection_association.id IN (SELECT history_dataset_collection_association.id
FROM history_dataset_collection_association JOIN implicit_collection_jobs ON implicit_collection_jobs.id = history_dataset_collection_association.implicit_collection_jobs_id JOIN implicit_collection_jobs_job_association ON implicit_collection_jobs.id = implicit_collection_jobs_job_association.implicit_collection_jobs_id
WHERE implicit_collection_jobs_job_association.job_id = %(job_id_1)s FOR UPDATE SKIP LOCKED)]
[parameters: {'update_time': datetime.datetime(2021, 4, 27, 15, 28, 36, 578357), 'job_id_1': 1082}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```